/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'macbook' at '5/1/16 6:55 PM' with Gradle 2.10
 *
 * @author macbook, @date 5/1/16 6:55 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
